"""empty message

Revision ID: 6782e75db45b
Revises: aab92b537062
Create Date: 2018-07-30 23:40:43.550353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6782e75db45b'
down_revision = 'aab92b537062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pwd', sa.String(length=100), nullable=True))
    op.drop_column('admin', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('_password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('admin', 'pwd')
    # ### end Alembic commands ###
