"""empty message

Revision ID: aab92b537062
Revises: 81b50c74d282
Create Date: 2018-07-29 09:22:21.419363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aab92b537062'
down_revision = '81b50c74d282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', sa.String(length=100), nullable=True))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###
